### ISSUE TITLE
Unknown column in table 'issues_ext_jira'

### ISSUE THREAD

**Issue by albertinisg** [MetricsGrimoire/Bicho#145]
In several dashboards, there's an error that stop the process:

<pre>
DBG: [06/Feb/2015-05:55:34] Bicho object created, options and backend initialized
Running Bicho with delay of 1 seconds
No account data provided. Not logged in Jira
Traceback (most recent call last):
  File "/usr/local/bin/bicho", line 25, in <module>
    retval = bicho.main.main()
  File "/usr/local/lib/python2.7/dist-packages/bicho/main.py", line 56, in main
    backend.run()
  File "/usr/local/lib/python2.7/dist-packages/bicho/backends/jira.py", line 947, in run
    self.last_mod_date = bugsdb.get_last_modification_date(tracker_id=dbtrk.id)
  File "/usr/local/lib/python2.7/dist-packages/bicho/db/database.py", line 243, in get_last_modification_date
    return self.backend.get_last_modification_date(self.store, tracker_id)
  File "/usr/local/lib/python2.7/dist-packages/bicho/backends/jira.py", line 203, in get_last_modification_date
    if result.is_empty():
  File "/usr/lib/python2.7/dist-packages/storm/store.py", line 1058, in is_empty
    result = self._store._connection.execute(select)
  File "/usr/lib/python2.7/dist-packages/storm/databases/mysql.py", line 106, in execute
    return Connection.execute(self, statement, params, noresult)
  File "/usr/lib/python2.7/dist-packages/storm/database.py", line 238, in execute
    raw_cursor = self.raw_execute(statement, params)
  File "/usr/lib/python2.7/dist-packages/storm/database.py", line 322, in raw_execute
    self._check_disconnect(raw_cursor.execute, *args)
  File "/usr/lib/python2.7/dist-packages/storm/database.py", line 371, in _check_disconnect
    return function(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1054, "Unknown column 'issues_ext_jira.fix_version' in 'field list'")
</pre>

Launching bicho against a new db fixes the error, or even adding this column by hand works.

**Comment by sduenas** [comment]
This is not a bug. Newest versions of Bicho support this new field. See #138 comments to know how to fix this problem.

**Comment by albertinisg** [comment]
Great! Didn't know it was fixed :) thanks!
