### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by yakomoz** [MetricsGrimoire/Bicho#149]
Hi,

I got a installation error after running "python setup.py install"

Command line Output:
----------------------------
running install
running build
running build_py
running build_scripts
running install_lib
running install_scripts
running install_data
Traceback (most recent call last):
  File "setup.py", line 35, in <module>
    scripts=["bin/bicho"])
  File "C:\Python2792\python-2.7.9\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python2792\python-2.7.9\lib\distutils\dist.py", line 953, in run_comm
ands
    self.run_command(cmd)
  File "C:\Python2792\python-2.7.9\lib\distutils\dist.py", line 972, in run_comm
and
    cmd_obj.run()
  File "C:\Python2792\python-2.7.9\lib\distutils\command\install.py", line 575,
in run
    self.run_command(cmd_name)
  File "C:\Python2792\python-2.7.9\lib\distutils\cmd.py", line 326, in run_comma
nd
    self.distribution.run_command(command)
  File "C:\Python2792\python-2.7.9\lib\distutils\dist.py", line 972, in run_comm
and
    cmd_obj.run()
  File "C:\Python2792\python-2.7.9\lib\distutils\command\install_data.py", line
58, in run
    dir = convert_path(f[0])
  File "C:\Python2792\python-2.7.9\lib\distutils\util.py", line 126, in convert_
path
    raise ValueError, "path '%s' cannot end with '/'" % pathname
ValueError: path 'share/man/man1/' cannot end with '/'

**Comment by sduenas** [comment]
This should be fixed by #148 . Please, try it and let us know whether it solved your problem or not.

**Comment by yakomoz** [comment]
Yes now the installation worked. Thank you.
But if I call "bicho" in command line it says "command not found". I thought that I can start bicho on command line or have I to reference it separably? Btw I use Win7 64bit.

Installation output:
running install
running build
running build_py
creating build
creating build\lib
creating build\lib\bicho
copying bicho\common.py -> build\lib\bicho
copying bicho\config.py -> build\lib\bicho
copying bicho\info.py -> build\lib\bicho
copying bicho\main.py -> build\lib\bicho
copying bicho\utils.py -> build\lib\bicho
copying bicho\__init__.py -> build\lib\bicho
creating build\lib\bicho\backends
copying bicho\backends\allura.py -> build\lib\bicho\backends
copying bicho\backends\bg.py -> build\lib\bicho\backends
copying bicho\backends\gerrit.py -> build\lib\bicho\backends
copying bicho\backends\github.py -> build\lib\bicho\backends
copying bicho\backends\googlecode.py -> build\lib\bicho\backends
copying bicho\backends\jira.py -> build\lib\bicho\backends
copying bicho\backends\lp.py -> build\lib\bicho\backends
copying bicho\backends\redmine.py -> build\lib\bicho\backends
copying bicho\backends\sf.py -> build\lib\bicho\backends
copying bicho\backends\storyboard.py -> build\lib\bicho\backends
copying bicho\backends\__init__.py -> build\lib\bicho\backends
creating build\lib\bicho\db
copying bicho\db\database.py -> build\lib\bicho\db
copying bicho\db\mysql.py -> build\lib\bicho\db
copying bicho\db\__init__.py -> build\lib\bicho\db
creating build\lib\bicho\post_processing
copying bicho\post_processing\issues_log.py -> build\lib\bicho\post_processing
copying bicho\post_processing\issues_log_bg.py -> build\lib\bicho\post_processin
g
copying bicho\post_processing\issues_log_gerrit.py -> build\lib\bicho\post_proce
ssing
copying bicho\post_processing\issues_log_jira.py -> build\lib\bicho\post_process
ing
copying bicho\post_processing\issues_log_lp.py -> build\lib\bicho\post_processin
g
copying bicho\post_processing\issues_log_redmine.py -> build\lib\bicho\post_proc
essing
copying bicho\post_processing\logtable.py -> build\lib\bicho\post_processing
copying bicho\post_processing\__init__.py -> build\lib\bicho\post_processing
running build_scripts
creating build\scripts-2.7
copying and adjusting bin\bicho -> build\scripts-2.7
running install_lib
copying build\lib\bicho\backends\allura.py -> C:\Python2792\python-2.7.9\Lib\sit
e-packages\bicho\backends
copying build\lib\bicho\backends\bg.py -> C:\Python2792\python-2.7.9\Lib\site-pa
ckages\bicho\backends
copying build\lib\bicho\backends\gerrit.py -> C:\Python2792\python-2.7.9\Lib\sit
e-packages\bicho\backends
copying build\lib\bicho\backends\github.py -> C:\Python2792\python-2.7.9\Lib\sit
e-packages\bicho\backends
copying build\lib\bicho\backends\googlecode.py -> C:\Python2792\python-2.7.9\Lib
\site-packages\bicho\backends
copying build\lib\bicho\backends\jira.py -> C:\Python2792\python-2.7.9\Lib\site-
packages\bicho\backends
copying build\lib\bicho\backends\lp.py -> C:\Python2792\python-2.7.9\Lib\site-pa
ckages\bicho\backends
copying build\lib\bicho\backends\redmine.py -> C:\Python2792\python-2.7.9\Lib\si
te-packages\bicho\backends
copying build\lib\bicho\backends\sf.py -> C:\Python2792\python-2.7.9\Lib\site-pa
ckages\bicho\backends
copying build\lib\bicho\backends\storyboard.py -> C:\Python2792\python-2.7.9\Lib
\site-packages\bicho\backends
copying build\lib\bicho\backends\__init__.py -> C:\Python2792\python-2.7.9\Lib\s
ite-packages\bicho\backends
copying build\lib\bicho\common.py -> C:\Python2792\python-2.7.9\Lib\site-package
s\bicho
copying build\lib\bicho\config.py -> C:\Python2792\python-2.7.9\Lib\site-package
s\bicho
copying build\lib\bicho\db\database.py -> C:\Python2792\python-2.7.9\Lib\site-pa
ckages\bicho\db
copying build\lib\bicho\db\mysql.py -> C:\Python2792\python-2.7.9\Lib\site-packa
ges\bicho\db
copying build\lib\bicho\db\__init__.py -> C:\Python2792\python-2.7.9\Lib\site-pa
ckages\bicho\db
copying build\lib\bicho\info.py -> C:\Python2792\python-2.7.9\Lib\site-packages\
bicho
copying build\lib\bicho\main.py -> C:\Python2792\python-2.7.9\Lib\site-packages\
bicho
copying build\lib\bicho\post_processing\issues_log.py -> C:\Python2792\python-2.
7.9\Lib\site-packages\bicho\post_processing
copying build\lib\bicho\post_processing\issues_log_bg.py -> C:\Python2792\python
-2.7.9\Lib\site-packages\bicho\post_processing
copying build\lib\bicho\post_processing\issues_log_gerrit.py -> C:\Python2792\py
thon-2.7.9\Lib\site-packages\bicho\post_processing
copying build\lib\bicho\post_processing\issues_log_jira.py -> C:\Python2792\pyth
on-2.7.9\Lib\site-packages\bicho\post_processing
copying build\lib\bicho\post_processing\issues_log_lp.py -> C:\Python2792\python
-2.7.9\Lib\site-packages\bicho\post_processing
copying build\lib\bicho\post_processing\issues_log_redmine.py -> C:\Python2792\p
ython-2.7.9\Lib\site-packages\bicho\post_processing
copying build\lib\bicho\post_processing\logtable.py -> C:\Python2792\python-2.7.
9\Lib\site-packages\bicho\post_processing
copying build\lib\bicho\post_processing\__init__.py -> C:\Python2792\python-2.7.
9\Lib\site-packages\bicho\post_processing
copying build\lib\bicho\utils.py -> C:\Python2792\python-2.7.9\Lib\site-packages
\bicho
copying build\lib\bicho\__init__.py -> C:\Python2792\python-2.7.9\Lib\site-packa
ges\bicho
running install_scripts
copying build\scripts-2.7\bicho -> C:\Python2792\python-2.7.9\Scripts
running install_data
copying doc\bicho.1 -> C:\Python2792\python-2.7.9\share\man\man1
running install_egg_info
Writing C:\Python2792\python-2.7.9\Lib\site-packages\Bicho-0.9-py2.7.egg-info

**Comment by sduenas** [comment]
I think the command was installed under your `C:\Python2792\python-2.7.9\Scripts` directory. Go there and run it.

**Comment by yakomoz** [comment]
Your right. There is a "bicho" file in C:\Python2792\python-2.7.9\Scripts.
![unbenannt](https://cloud.githubusercontent.com/assets/9658596/7471850/25a7533e-f32c-11e4-9e33-bb1e294e9e30.PNG)

But in command line bicho is still an unknown command.
C:\Python2792\python-2.7.9\Scripts>bicho
Der Befehl "bicho" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

C:\Python2792\python-2.7.9\Scripts>bicho --help
Der Befehl "bicho" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

**Comment by yakomoz** [comment]
bicho is installed in site-packages and in the scripts folder. but there is no executable .bat/.exe file in scripts. is that the problem?

**Comment by sduenas** [comment]
No idea. I don't use Windows since 2005 or so. Have you try to run `python bicho` on scripts folder?

**Comment by yakomoz** [comment]
Yes. It does not work.

C:\Python2792\python-2.7.9\Scripts>python bicho
Traceback (most recent call last):
  File "bicho", line 25, in <module>
    retval = bicho.main.main()
  File "C:\Python2792\python-2.7.9\lib\site-packages\bicho\main.py", line 45, in
 main
    Config.set_config_options(usage)
  File "C:\Python2792\python-2.7.9\lib\site-packages\bicho\config.py", line 257,
 in set_config_options
    Config.load()  # try to load a config file from default locations
  File "C:\Python2792\python-2.7.9\lib\site-packages\bicho\config.py", line 85,
in load
    config_file = os.path.join(bicho_dot_dir(), 'config')
  File "C:\Python2792\python-2.7.9\lib\site-packages\bicho\utils.py", line 122,
in bicho_dot_dir
    dot_dir = os.path.join(os.environ.get('HOME'), '.bicho')
  File "C:\Python2792\python-2.7.9\lib\ntpath.py", line 64, in join
    result_drive, result_path = splitdrive(path)
  File "C:\Python2792\python-2.7.9\lib\ntpath.py", line 114, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()
