### ISSUE TITLE
Error reading milestone's code name

### ISSUE THREAD

**Issue by sanacl** [MetricsGrimoire/Bicho#2]
Stefano Maffulli sent us this bug:

```
Error in function analyzeBug with URL: '
'https://bugs.launchpad.net/openstack and Bug:
https://api.launchpad.net/1.0/nova/+bug/989764
Traceback (most recent call last):
  File "/usr/local/bin/bicho", line 25, in <module>
    retval = Bicho.main.main()
  File "/usr/local/lib/python2.7/dist-packages/Bicho/main.py", line 54, in main
    backend.run()
  File "/usr/local/lib/python2.7/dist-packages/Bicho/backends/lp.py",
line 997, in run
    issue_data = self.analyze_bug(bug)
  File "/usr/local/lib/python2.7/dist-packages/Bicho/backends/lp.py",
line 823, in analyze_bug
    issue.set_milestone_code_name(bug.milestone.code_name)
  File "/usr/lib/python2.7/dist-packages/lazr/restfulclient/resource.py",
line 688, in __getattr__
    return super(Entry, self).__getattr__(name)
  File "/usr/lib/python2.7/dist-packages/lazr/restfulclient/resource.py",
line 331, in __getattr__
    return self.lp_get_parameter(attr)
  File "/usr/lib/python2.7/dist-packages/lazr/restfulclient/resource.py",
line 215, in lp_get_parameter
    self._ensure_representation()
  File "/usr/lib/python2.7/dist-packages/lazr/restfulclient/resource.py",
line 357, in _ensure_representation
    representation = self._root._browser.get(self._wadl_resource)
  File "/usr/lib/python2.7/dist-packages/lazr/restfulclient/_browser.py",
line 291, in get
    response, content = self._request(url, extra_headers=headers)
  File "/usr/lib/python2.7/dist-packages/lazr/restfulclient/_browser.py",
line 242, in _request
    str(url), method=method, body=data, headers=headers)
  File "/usr/lib/python2.7/dist-packages/lazr/restfulclient/_browser.py",
line 211, in _request_and_retry
    url, method=method, body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line
1346, in request
    info, content = cached_value.split('\r\n\r\n', 1)
ValueError: need more than 1 value to unpack
```

**Comment by newtoncalegari** [comment]
Hello,
Is there any advice on how to solve this issue?

**Comment by sanacl** [comment]
@newtoncalegari this software is no longer maintained. We are switching to a new set of tools. The one we use to gather information is called Perceval. Have a look at https://github.com/grimoirelab/perceval
